#!/usr/bin/env tsx
// Regenerate the AUTO section of CLAUDE.md from the current catalog state.
// Idempotent and safe to re-run any time. Replaces only the content between:
//
//   <!-- AUTO:catalog-stats -->
//   <!-- /AUTO:catalog-stats -->
//
// Anything outside those markers is left untouched.
//
// Wired into tools/synthesize.ts so adding a competitor + running synthesize
// also refreshes CLAUDE.md. Can also be run standalone:
//
//   npx tsx tools/build-claude-md.ts

import { readFile, writeFile } from 'node:fs/promises'
import { existsSync } from 'node:fs'
import path from 'node:path'

const ROOT = path.resolve(path.dirname(new URL(import.meta.url).pathname), '..')
const CLAUDE_MD = path.join(ROOT, 'CLAUDE.md')
const CATALOG_JSON = path.join(ROOT, '00_Market_Overview', 'competitor_catalog.json')
const PAGES_JSON = path.join(ROOT, '00_Market_Overview', 'pages_by_kind.json')

const START_MARKER = '<!-- AUTO:catalog-stats -->'
const END_MARKER = '<!-- /AUTO:catalog-stats -->'

export async function buildClaudeMd(opts: { quiet?: boolean } = {}): Promise<void> {
  const log = (msg: string) => { if (!opts.quiet) console.log(msg) }

  if (!existsSync(CLAUDE_MD)) {
    console.warn(`[build-claude-md] CLAUDE.md not found at ${CLAUDE_MD} — skipping`)
    return
  }
  if (!existsSync(CATALOG_JSON)) {
    console.warn(`[build-claude-md] ${CATALOG_JSON} missing — run synthesize.ts first`)
    return
  }
  if (!existsSync(PAGES_JSON)) {
    console.warn(`[build-claude-md] ${PAGES_JSON} missing — run build-page-index.ts first`)
    return
  }

  const catalog: any[] = JSON.parse(await readFile(CATALOG_JSON, 'utf8'))
  const pages: any = JSON.parse(await readFile(PAGES_JSON, 'utf8'))

  const blogByFirm: Record<string, number> = {}
  for (const e of pages.kind?.blog_post || []) {
    if (e?.firm) blogByFirm[e.firm] = (blogByFirm[e.firm] || 0) + 1
  }

  const allFirms = catalog.map(c => c.slug).filter(Boolean).sort()
  const firmsWithCorpus = Object.keys(blogByFirm).sort()
  const firmsWithoutCorpus = allFirms.filter(f => !blogByFirm[f])
  const totalBlogPosts = Object.values(blogByFirm).reduce((a, b) => a + b, 0)
  const totalSitePages = pages.totals?.site_pages ?? 0
  const totalFirms = catalog.length

  // jurisdiction tally
  const jurTally: Record<string, number> = {}
  for (const c of catalog) {
    const j = c.regulatory_jurisdiction || c.jurisdiction || 'unknown'
    jurTally[j] = (jurTally[j] || 0) + 1
  }
  const jurStr = Object.entries(jurTally)
    .sort((a, b) => b[1] - a[1])
    .map(([k, v]) => `${k}:${v}`)
    .join(' · ')

  const today = new Date().toISOString().slice(0, 10)

  const block = [
    `*As of ${today}* — ${totalFirms} competitors profiled · ${firmsWithCorpus.length} firms with \`Knowledge_From_Source/\` corpora (~${totalBlogPosts} blog posts captured) · ${totalSitePages} site pages indexed in \`00_Market_Overview/pages_by_kind.json\`.`,
    '',
    `**Jurisdictions:** ${jurStr || '(none)'}`,
    '',
    `**Firms WITH a blog/article corpus** (read \`Competitors/<Firm>/Knowledge_From_Source/_index.json\` to enumerate posts):`,
    '',
    firmsWithCorpus.length ? firmsWithCorpus.map(f => `- ${f}`).join('\n') : '- (none)',
    '',
    `**Firms WITHOUT a blog corpus** (don't ask for their blog posts — read \`Source_Data/pages/\` or \`2_Full_Profile.md\` instead):`,
    '',
    firmsWithoutCorpus.length ? firmsWithoutCorpus.map(f => `- ${f}`).join('\n') : '- (none)',
    '',
    `*This block is regenerated by \`tools/build-claude-md.ts\` — invoked automatically at the end of \`tools/synthesize.ts\`.*`
  ].join('\n')

  const original = await readFile(CLAUDE_MD, 'utf8')
  const startIdx = original.indexOf(START_MARKER)
  const endIdx = original.indexOf(END_MARKER)
  if (startIdx === -1 || endIdx === -1 || endIdx < startIdx) {
    throw new Error(`[build-claude-md] CLAUDE.md missing AUTO markers — refusing to overwrite`)
  }

  const before = original.slice(0, startIdx + START_MARKER.length)
  const after = original.slice(endIdx)
  const next = `${before}\n${block}\n${after}`

  if (next !== original) {
    await writeFile(CLAUDE_MD, next)
    log(`[build-claude-md] updated CLAUDE.md — ${totalFirms} firms · ${firmsWithCorpus.length} corpora · ${totalBlogPosts} posts`)
  } else {
    log(`[build-claude-md] CLAUDE.md already up-to-date`)
  }
}

// Run as a CLI when invoked directly.
const argv1 = process.argv[1] || ''
if (argv1.endsWith('build-claude-md.ts') || argv1.endsWith('build-claude-md.js')) {
  buildClaudeMd().catch(err => {
    console.error(err)
    process.exit(1)
  })
}
